[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
toml = "0.8.19"
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
game_of_drones = { git = "https://github.com/AP-Game-Of-Drones/GoD_Library.git" }